<a href="https://colab.research.google.com/github/byOKO/Deep_Learning/blob/main/1107_DeepLearning2_OR.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**11월 7일 인공지능 심화과정**

실습 2. OR Function

In [ ]:
#1. 패키지 가져오기
import numpy as np

print(np.__version__)

1.18.5


In [ ]:
#2. 데이터 만들기

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[1],[1],[1]])

print(X)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [1]
 [1]
 [1]]


In [ ]:
#3. Keras 패키지 불러오기

from tensorflow import keras
from tensorflow.keras import layers

print(keras.__version__)

2.4.0


In [ ]:
#4. Network 설정

model = keras.Sequential() # 빈 모델

model.add(layers.Dense(units= 1,input_dim=2)) #단일 퍼셉트론(입력받자마자 출력)
model.add(layers.Activation('sigmoid'))

model.summary() #parameter = weight + bias (input*units + 1)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 3         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#5. compile(Loss+Optimizer)

model.compile(loss='binary_crossentropy',
              optimizer='sgd')

In [ ]:
#6.모델 학습

model.fit(X,y,batch_size= 1,epochs=500)


Epoch 1/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6196
Epoch 2/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6144
Epoch 3/500
4/4 [==============================] - 0s 2ms/step - loss: 0.6093
Epoch 4/500
4/4 [==============================] - 0s 1ms/step - loss: 0.6043
Epoch 5/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5995
Epoch 6/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5948
Epoch 7/500
4/4 [==============================] - 0s 2ms/step - loss: 0.5902
Epoch 8/500
4/4 [==============================] - 0s 1ms/step - loss: 0.5857
Epoch 9/500
4/4 [==============================] - 0s 2ms/step - loss: 0.5814
Epoch 10/500
4/4 [==============================] - 0s 2ms/step - loss: 0.5771
Epoch 11/500
4/4 [==============================] - 0s 2ms/step - loss: 0.5730
Epoch 12/500
4/4 [==============================] - 0s 2ms/step - loss: 0.5690
Epoch 13/500
4/4 [==============================] - 0s 1ms/st

In [ ]:
#7. 모델 Test

test_data = np.array([[0,1],[1,1],[0,0]])

result = model.predict_classes(test_data)
print(result)

[[1]
 [1]
 [0]]
