<a href="https://colab.research.google.com/github/byOKO/Deep_Learning/blob/main/1107_DeepLearning1_And.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**11월 7일 인공지능 심화과정**

실습 1. And Function

In [ ]:
#1. 패키지 가져오기
import numpy as np

print(np.__version__)

1.18.5


In [ ]:
#2. 데이터 만들기

X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[0],[0],[0],[1]])

print(X)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
[[0]
 [0]
 [0]
 [1]]


In [ ]:
#3. Keras 패키지 불러오기

from tensorflow import keras
from tensorflow.keras import layers

print(keras.__version__)

2.4.0


In [ ]:
#4. Network 설정

model = keras.Sequential() # 빈 모델

model.add(layers.Dense(units= 1,input_dim=2)) #단일 퍼셉트론(입력받자마자 출력)
model.add(layers.Activation('sigmoid'))

model.summary() #parameter = weight + bias (input*units + 1)


Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 1)                 3         
_________________________________________________________________
activation_3 (Activation)    (None, 1)                 0         
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#5. compile(Loss+Optimizer)

model.compile(loss='binary_crossentropy',
              optimizer='sgd')

In [ ]:
#6.모델 학습

model.fit(X,y,batch_size= 1,epochs=200)

Epoch 1/200
4/4 [==============================] - 0s 1ms/step - loss: 0.9327
Epoch 2/200
4/4 [==============================] - 0s 2ms/step - loss: 0.9208
Epoch 3/200
4/4 [==============================] - 0s 2ms/step - loss: 0.9092
Epoch 4/200
4/4 [==============================] - 0s 3ms/step - loss: 0.8978
Epoch 5/200
4/4 [==============================] - 0s 1ms/step - loss: 0.8865
Epoch 6/200
4/4 [==============================] - 0s 1ms/step - loss: 0.8755
Epoch 7/200
4/4 [==============================] - 0s 2ms/step - loss: 0.8647
Epoch 8/200
4/4 [==============================] - 0s 1ms/step - loss: 0.8541
Epoch 9/200
4/4 [==============================] - 0s 1ms/step - loss: 0.8437
Epoch 10/200
4/4 [==============================] - 0s 1ms/step - loss: 0.8335
Epoch 11/200
4/4 [==============================] - 0s 2ms/step - loss: 0.8235
Epoch 12/200
4/4 [==============================] - 0s 2ms/step - loss: 0.8136
Epoch 13/200
4/4 [==============================] - 0s 2ms/st

In [ ]:
#7. 모델 Test

test_data = np.array([[0,1],[1,1],[0,0]])

result = model.predict(test_data)
print(result)

[[0.36926946]
 [0.22126567]
 [0.44095737]]


In [ ]:
result2 = model.predict_classes(test_data)
print(result2)

[[0]
 [1]
 [0]]


In [ ]:
#8. 모델 살펴보기

print(model.get_weights())

[array([[1.0619   ],
       [0.8449842]], dtype=float32), array([-1.7076058], dtype=float32)]
